packages:
  darwin:
    taps:
      - jandedobbeleer/oh-my-posh
    brews:
      - bat
      - chafa
      - curl
      - eza
      - fd
      - fzf
      - gh
      - git
      - git-delta
      - gnupg
      - jq
      - lsd
      - neofetch
      - neovim
      - oh-my-posh
      - pass
      - pfetch
      - pinentry-mac
      - pre-commit
      - ripgrep
      - shellcheck
      - shfmt
      - tmux
      - tree
      - unzip
      - w3m
      - wget
      - zsh
      - zsh-autosuggestions
      - zsh-history-substring-search
      - zsh-syntax-highlighting
    casks:
      - font-jetbrains-mono-nerd-font
      - ghostty
      - iterm2
      - kitty
      - claude-code
  linux:
    apt:
      - bat
      - build-essential
      - ca-certificates
      - chafa
      - curl
      - desktop-file-utils
      - fd-find
      - file
      - flatpak
      - fonts-jetbrains-mono
      - fzf
      - gh
      - git
      - git-delta
      - gnome-keyring
      - gnupg
      - jq
      - libsecret-1-0
      - libsecret-1-dev
      - neofetch
      - neovim
      - openssh-client
      - openssh-server
      - pass
      - openssl
      - pcscd
      - pinentry-curses
      - pinentry-gnome3
      - picom
      - pkg-config
      - scdaemon
      - ripgrep
      - shellcheck
      - shfmt
      - snapd
      - tmux
      - tree
      - unzip
      - w3m
      - wget
      - xdg-utils
      - zsh
      - zsh-autosuggestions
      - zsh-syntax-highlighting
