"""Constants and patterns for Claude Code hooks."""

PROTECTED_PATTERNS = [
    "*.env",
    "*.env.*",
    "*/.env",
    "*/.env.*",
    "*credentials*",
    "*secrets*",
    "*.pem",
    "*.key",
    "*.crt",
    "*id_rsa*",
    "*id_ed25519*",
    ".git/*",
    "*/.git/*",
    "package-lock.json",
    "yarn.lock",
    "Cargo.lock",
    "uv.lock",
    "poetry.lock",
    ".vscode/settings.json",
    ".idea/*",
]

SECRET_PATTERNS = [
    r"AKIA[0-9A-Z]{16}",
    r"sk-[a-zA-Z0-9]{48}",
    r"sk-proj-[a-zA-Z0-9\-]{80,}",
    r"ghp_[a-zA-Z0-9]{36}",
    r"gho_[a-zA-Z0-9]{36}",
    r"github_pat_[a-zA-Z0-9]{22}_[a-zA-Z0-9]{59}",
    r"xox[baprs]-[a-zA-Z0-9\-]+",
    r"sk_live_[a-zA-Z0-9]+",
    r"rk_live_[a-zA-Z0-9]+",
]

DANGEROUS_PATTERNS = [
    r"rm -rf /$",
    r"rm -rf /\*",
    r"rm -rf ~",
    r"rm -rf ~/\*",
    r"rm -rf \$HOME",
    r"rm -rf \.$",
    r"rm -rf \.\.",
    r"rm -rf \./\*",
    r"mkfs",
    r"dd if=.* of=/dev/",
    r"> /dev/sd",
    r"chmod -R 777 /",
    r"chown -R .* /",
    r":\(\)\{ :\|:& \};:",
    r"fork while fork",
    r"history -c",
    r"shred.*history",
    r"shred.*bash_history",
    r"git push.*--force.*main",
    r"git push.*--force.*master",
    r"git push.*-f.*main",
    r"git push.*-f.*master",
    r"git reset --hard.*origin/main",
    r"git reset --hard.*origin/master",
]

JAX_LIBS = [
    "jax",
    "jax.numpy",
    "jax.lax",
    "jax.random",
    "jax.nn",
    "flax.nnx",
    "flax.linen",
    "optax",
    "orbax",
    "orbax.checkpoint",
    "jaxtyping",
    "grain",
    "chex",
    "equinox",
    "fiddle",
    "langchain",
    "transformers",
    "anthropic",
    "openai",
]

KNOWN_LIBS = [
    "jax",
    "flax",
    "optax",
    "orbax",
    "grain",
    "jaxtyping",
    "chex",
    "equinox",
    "pydantic",
    "fastapi",
    "pytest",
    "numpy",
    "pandas",
    "transformers",
    "torch",
    "pytorch",
    "tensorflow",
    "langchain",
    "openai",
    "anthropic",
    "httpx",
    "sqlalchemy",
    "redis",
    "celery",
    "aiohttp",
    "requests",
    "django",
    "flask",
]

PROTECTED_BRANCHES = ["main", "master", "production", "prod", "release", "develop"]

SOURCE_EXTENSIONS = {".py", ".ts", ".tsx", ".js", ".jsx", ".rs", ".go", ".java"}
